### ISSUE TITLE
Issues to compile ESM4-07/01/2022

### ISSUE THREAD

**Issue by JFA-Mbule** [NOAA-GFDL/ESM4#10]
Hi, I'm again, Jaime. My institution's supercomputing support staff were able to install the listed packages as needed to compile the model. I tested and managed to compile and generate the executable, the esm4.1.x file. However, during the compilation it gave some errors related to 'mpich2-c' were found, which I will list below:

**_No package 'mpich2-c' found_
Package mpich2-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `mpich2-c.pc'
to the PKG_CONFIG_PATH environment variable
No package 'mpich2-c' found
mpiifort -DINTERNAL_FILE_NML -fpp -Wp,-w  -I/scratch/app/netcdf/4.6_openmpi-2.0_intel/include   -fno-alias -stack-temps -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -g -sox -traceback -fp-model source -O3 -xsse2 -qoverride-limits -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/atmos_dyn -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/sis2 -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/icebergs -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/atmos_cubed_sphere -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/atmos_phys -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/mom6 -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/lm4P -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/fms/build/.mods  -c	/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/src/coupler/full/flux_exchange.F90
Package mpich2-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `mpich2-c.pc'
to the PKG_CONFIG_PATH environment variable
_No package 'mpich2-c' found_
Package mpich2-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `mpich2-c.pc'
to the PKG_CONFIG_PATH environment variable
No package 'mpich2-c' found
mpiifort -DINTERNAL_FILE_NML -fpp -Wp,-w  -I/scratch/app/netcdf/4.6_openmpi-2.0_intel/include   -fno-alias -stack-temps -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -g -sox -traceback -fp-model source -O3 -xsse2 -qoverride-limits -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/atmos_dyn -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/sis2 -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/icebergs -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/atmos_cubed_sphere -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/atmos_phys -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/mom6 -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/lm4P -I/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/fms/build/.mods  -c	/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/src/coupler/full/coupler_main.F90
Package mpich2-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `mpich2-c.pc'**

**make[1]: Leaving the directory `/prj/cptec/jaime.antonio/These_JFA/Models/ESM4_Model/ESM4/exec/coupler'
mpiifort coupler/libcoupler.a atmos_dyn/libatmos_dyn.a sis2/libsis2.a atmos_cubed_sphere/libatmos_cubed_sphere.a mom6/libmom6.a icebergs/libicebergs.a lm4P/liblm4P.a atmos_phys/libatmos_phys.a fms/build/libFMS/.libs/ libFMS.a -qopenmp -L/scratch/app/netcdf/4.6_openmpi-2.0_intel/lib -lnetcdff -L/scratch/app/netcdf/4.6_openmpi-2.0_intel/lib -L/scratch/app/pnetcdf/1.10_openmpi -2.0_intel/lib -L/scratch/app/hdf5/1.8_openmpi-2.0_intel/lib -lnetcdf -lnetcdf -lhdf5_hl -lhdf5 -lz -L/scratch/app/netcdf/4.6_openmpi-2.0_intel/lib -lnetcdf - lmkl_blas95_lp64 -lmkl_lapack95_lp64 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -o esm4.1.x
Package mpich2-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `mpich2-c.pc'
to the PKG_CONFIG_PATH environment variable
_No package 'mpich2-c' found_
ld: warning: libmpi.so.20, needed by /scratch/app/netcdf/4.6_openmpi-2.0_intel/lib/libnetcdff.so, may conflict with libmpi.so.12
[jaime.antonio@sdumont14 exec]$ ls**

Perhaps, the absence of this package, can be a big problem so that the executable works very well? Or since the .x file was generated (which by the way, with 166Mb), but I don't sure if it will work relatively well when running the model?!

Please, can you tell me something about this?!

**Comment by thomas-robinson** [comment]
```
No package 'mpich2-c' found
Package mpich2-c was not found in the pkg-config search path.
Perhaps you should add the directory containing mpich2-c.pc' to the PKG_CONFIG_PATH environment variable 
No package 'mpich2-c' found
```
This is a warning related to pkg-config.  The .mk file uses `pkg-config` to try to figure out hot to include the MPI libraries.  I see this warning a lot when compiling and typically just ignore it. 

The `ld: warning: libmpi.so.20, needed by /scratch/app/netcdf/4.6_openmpi-2.0_intel/lib/libnetcdff.so, may conflict with libmpi.so.12` warning may be more of an issue, but this is a system/netcdf/mpi issue, not an ESM issue.  

Since you have a .x file, you should probably just try to run it.  If there are issue with the libraries at run time (like a .so missing or a library conflict), you will need to consult someone local to help you get the linking correct when you compile, or rebuild the libraries to that they are all compatible.
